name: homekru_owner
description: 'A Flutter application for household management, allowing owners to manage helpers, assign tasks, track attendance, and monitor household operations.'
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  flutter_screenutil: ^5.9.3
  flutter_otp_text_field: ^1.1.1
  ionicons: ^0.2.1
  dropdown_search: ^6.0.2
  go_router: ^16.2.0
  image_picker: ^1.2.0
  dotted_border: ^3.1.0
  google_fonts: ^6.3.1
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.3
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tasks/
    - assets/images/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
