name: homekru_owner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  smooth_page_indicator: ^1.2.1
  flutter_screenutil: ^5.9.3
  awesome_drawer_bar: ^1.2.1
  flutter_zoom_drawer: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  ionicons: ^0.2.1
  eva_icons_flutter: ^3.0.0
  dropdown_search: ^6.0.2
  go_router: ^16.2.0
  image_picker: ^1.2.0
  syncfusion_flutter_charts: ^31.1.19
  dotted_border: ^3.1.0
  google_fonts: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/tasks/
    - assets/images/svgs/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

